// Code generated by clickhouse-gen. DO NOT EDIT.

package example

import (
	"time"
)

//ExampleTable
type ExampleTable struct {
	Udid            string    `db:"udid" json:"udid,omitempty"`
	Device          string    `db:"device" json:"device,omitempty"`
	DeviceHeight    int8      `db:"device_height" json:"device_height,omitempty"`
	DeviceWidth     int8      `db:"device_width" json:"device_width,omitempty"`
	DeviceOsversion float32   `db:"device_osversion" json:"device_osversion,omitempty"`
	DeviceAccount   string    `db:"device_account" json:"device_account,omitempty"`
	DeviceProvider  string    `db:"device_provider" json:"device_provider,omitempty"`
	UserAgent       string    `db:"user_agent" json:"user_agent,omitempty"`
	Platform        string    `db:"platform" json:"platform,omitempty"`
	PlatformVersion string    `db:"platform_version" json:"platform_version,omitempty"`
	Browser         string    `db:"browser" json:"browser,omitempty"`
	BrowserVersion  string    `db:"browser_version" json:"browser_version,omitempty"`
	Ip              string    `db:"ip" json:"ip,omitempty"`
	Country         string    `db:"country" json:"country,omitempty"`
	City            string    `db:"city" json:"city,omitempty"`
	AppsPackage     []string  `db:"Apps.package" json:"Apps.package,omitempty"`
	EventDateTime   time.Time `db:"EventDateTime" json:"EventDateTime,omitempty"`
}

//GetQueryExampleTable
func GetQueryExampleTable() string {
	return "INSERT INTO example_table (udid,device,device_height,device_width,device_osversion,device_account,device_provider,user_agent,platform,platform_version,browser,browser_version,ip,country,city,Apps.package,EventDateTime) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
}

//GetArgs
func (model ExampleTable) GetArgs() []interface{} {
	r := make([]interface{}, 0)
	r = append(r,
		model.Udid,
		model.Device,
		model.DeviceHeight,
		model.DeviceWidth,
		model.DeviceOsversion,
		model.DeviceAccount,
		model.DeviceProvider,
		model.UserAgent,
		model.Platform,
		model.PlatformVersion,
		model.Browser,
		model.BrowserVersion,
		model.Ip,
		model.Country,
		model.City,
		model.AppsPackage,
		model.EventDateTime,
	)
	return r
}

//TableName
func (model ExampleTable) TableName() string {
	return "example_table"
}

//BaseName
func (model ExampleTable) BaseName() string {
	return "metrika"
}
